name: product_search
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  
  flutter_riverpod: ^2.5.3
  
  gap: ^3.0.1

  freezed_annotation: ^2.4.4
  freezed: ^2.5.2

  build_runner: ^2.4.9
  json_annotation: ^4.9.0
  
  flutter_portal: ^1.1.4

  camera: ^0.11.0+2

  photo_manager: ^3.5.1

  collection: ^1.18.0

  shared_preferences: ^2.2.3
  graphql_flutter: ^5.1.2
  image_picker: ^1.1.2

  path_provider: ^2.1.4
  path: ^1.9.0

  http_parser: ^4.0.2
  http: ^1.2.2
  mime: ^1.0.6

  flutter_svg: ^2.0.10+1

  flutter_box_transform: ^0.4.6

  styled_divider: ^1.0.5

  flutter_image_compress: ^2.3.0
  image: ^4.3.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0
  icons_launcher: ^3.0.0
  json_serializable: ^6.8.0
  spider: ^4.2.2

icons_launcher:
  image_path: "assets/icons/logotip.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    
